// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4 , duration: "10s", vus: 5};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "get start page",
    id: "4682d2a1-07b5-41b1-9916-027241ad1423",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "get signup page",
    id: "39db3dce-c312-418d-8eef-12c068553f4b",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/signup",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "registering a new user",
    id: "c66ee248-49cf-41e4-aacd-287aab5f65b2",
    method: "POST",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/register_user",
    data:
      '{\r\n\t"name": "Tester",\r\n\t"email": "test123@gmail.com",\r\n\t"password": "test123"\r\n}',
    post(response) {
      pm.test("Response time is less than 200ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(200);
      });
      pm.test("Content-Type is present", function() {
        pm.response.to.have.header("Content-Type");
      });
    }
  });

  postman[Request]({
    name: "get extended_signup page",
    id: "3e95c9f9-2a8a-48e6-a57b-0493823adc27",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/extended_signup",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "registering an existing user",
    id: "e26c1ba1-b09b-4399-a39a-7d8c42d78444",
    method: "POST",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/register_user",
    data:
      '{\r\n\t"name": "Tester",\r\n\t"email": "test123@gmail.com",\r\n\t"password": "test123"\r\n}',
    post(response) {
      pm.test("Response time is less than 200ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(200);
      });
      pm.test("Content-Type is present", function() {
        pm.response.to.have.header("Content-Type");
      });
    }
  });

  postman[Request]({
    name: "get login page",
    id: "42a05775-b421-4536-b768-e68543fe83a9",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "successful login attempt",
    id: "b1d3e8d1-a175-44e6-b517-f232b9bb3fe8",
    method: "POST",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/verify_login",
    data:
      '{\r\n\t"name": "Tester",\r\n\t"email": "test123@gmail.com",\r\n\t"password": "test123"\r\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("Response time is less than 200ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(200);
      });
    }
  });

  postman[Request]({
   name: "failed login attempt with wrong password",
   id: "c2841afd-eaad-4062-81a3-e40a28d63777",
   method: "POST",
  headers: {
     'Content-Type': 'application/json',
   },
   address: "http://127.0.0.1:5000/verify_login",
   data:
     '{\r\n\t"name": "Tester",\r\n\t"email": "test123@ail.com",\r\n\t"password": "wrong"\r\n}',
   post(response) {
     pm.test("Status code is 500", function() {
       pm.response.to.have.status(500);
     });
   }
  });

  postman[Request]({
    name: "get homepage",
    id: "84b61287-d222-46fd-9b65-2ed27912e5b1",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/homepage",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "get recommend page",
    id: "0baab8bf-6fce-4973-b53c-c1bb1cb7b4c7",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/recommend",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "get merch page",
    id: "fdf9b81f-b754-4e0a-aade-f1ca10c5c26e",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/merch",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "adding merchandise to cart",
    id: "29325ee8-7adc-4b40-83ba-d1b623968335",
    method: "POST",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/add_to_cart",
    data:
      '{\r\n\t"item":"Men Joggers",\r\n\t"cost":699,\r\n\t"category":"merchandise"\r\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("Your test name", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.status).to.eql(200);
      });
      pm.test("Response time is less than 200ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(200);
      });
      pm.test("Content-Type is present", function() {
        pm.response.to.have.header("Content-Type");
      });
    }
  });

  postman[Request]({
    name: "getting food page",
    id: "b1763831-d1a7-48d7-bee8-d809496b7c72",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/eat",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "adding food to cart",
    id: "c9a21d78-790f-49e1-a0d2-fe102a3146f1",
    method: "POST",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/add_to_cart",
    data:
      '{\r\n\t"item":"Men Joggers",\r\n\t"cost":699,\r\n\t"category":"food"\r\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("Your test name", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.status).to.eql(200);
      });
      pm.test("Response time is less than 200ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(200);
      });
      pm.test("Content-Type is present", function() {
        pm.response.to.have.header("Content-Type");
      });
    }
  });

  postman[Request]({
    name: "get workout page",
    id: "9608256f-00aa-4d7f-bf46-e0e110f80155",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/cult",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "adding workout to cart",
    id: "1547b442-1df5-4662-996a-3b46dc1861e4",
    method: "POST",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/add_to_cart",
    data:
      '{\r\n\t"item":"Zumba",\r\n\t"cost":350,\r\n\t"category":"session"\r\n}',
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("Your test name", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.status).to.eql(200);
      });
      pm.test("Response time is less than 200ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(200);
      });
      pm.test("Content-Type is present", function() {
        pm.response.to.have.header("Content-Type");
      });
    }
  });

  postman[Request]({
    name: "getting cart page",
    id: "a0968588-d4f9-4554-bf52-8fef79cd6319",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/cart",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "get payment page",
    id: "0f7aaf99-3ded-4654-864b-56012d43f204",
    method: "GET",
  headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/payment",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

}